---
- name: k8sCluster Create
  hosts: k8s
  become: True
  tasks: 
    - name: Disable Swap 01
      shell: swapoff -a
    - name: Disable Swap 02
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    - name: Disable selinux
      command: setenforce 0

    - name: Disable Selinux
      shell: sudo sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux

    - name: Disable Firewall
      systemd_service:
        name: firewalld
        state: stopped
        enabled: false

    - name: yum-utils install
      yum:
        name: yum-utils
        state: present

    - name: docker repository add
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: docker-ce install
      yum:
        name: docker-ce
        state: present

    - name: docker-ce-cli install
      yum:
        name: docker-ce-cli
        state: present
    
    - name: containerd.io install
      yum: 
        name: containerd.io
        state: present
    
    - name: docker-buildx-plugin install
      yum:
        name: docker-buildx-plugin
        state: present

    - name: docker-compose-plugin install
      yum:
        name: docker-compose-plugin
        state: present

    - name: enable docker & start
      systemd_service:
        name: docker
        state: started
        enabled: true

    - name: config modprobe
      shell: cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
           overlay
           br_netfilter
           EOF

    - name: config overlay
      modprobe:
        name: overlay
        state: present
        persistent: present

    - name: config br_netfilter
      modprobe:
        name: br_netfilter
        state: present
        persistent: present

    - name: configration k8s
      sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_file: /etc/sysctl.d/k8s.conf
        sysctl_set: true
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: containerd configure
      shell:
        containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
    
    - name: containerd Cgroup config
      shell:
        sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml


    - name: containerd restart & enable
      systemd_service:
        name: containerd
        state: restarted
        enabled: true
    
    - name: k8s repo add
      yum_repository:
        name: Kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
        gpgcheck: true
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
        description: kubernetes repository add
        exclude: 
          - kubelet
          - kubeadm
          - kubectl
          - cri-tools
          - kubernetes-cni

    - name: k8s install
      yum:
        name: "{{ item }}"
        state: present
        disable_excludes: Kubernetes
      loop:
        - kubelet
        - kubeadm
        - kubectl


